language: node_js
cache:
  directories:
  - "~/.npm"
node_js:
- 12
addons:
  ssh_known_hosts: 31.31.198.239
script: npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -v ${TRAVIS_BUILD_DIR}/public/ ${FTP_USER}@${FTP_HOST}:${FTP_PATH}
  on:
    branch: master
