language: node_js
node_js:
  - 12
before_script:
  - npm run lint
script: npm run build
after_success:
 - set -e
 - sudo apt-get install -y lftp
 - lftp -c "set ftps:initial-prot ''; set ftp:ssl-protect-data true; set ssl:verify-certificate false; set ftp:ssl-allow false; open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21; mirror -eRv $FTP_DIR .; quit;"
